### ISSUE TITLE
Not working with Xcode8

### ISSUE THREAD

**Issue by obrhoff** [yomajkel/ImageStream#2]
Hey,

I tried to get your project running. Unfurtunatly it only displays a message, that I should contact the vendor. Could you take a look?

**Comment by jbarros35** [comment]
Xcode 9 not working too, tried but not happening.

**Comment by jbarros35** [comment]
ld: warning: directory not found for option '-F/Users/Jose/Library/Developer/Xcode/DerivedData/ImageStreamWorkspace-gdibgrkstrdigzblgeofvqcezfrs/Build/Products/Debug/Alamofire'
ld: framework not found Alamofire
clang: error: linker command failed with exit code 1 (use -v to see invocation)
